/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Check */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/leads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Leads */
        get: operations["list_leads_api_v1_leads_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/leads/mine": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List My Leads */
        get: operations["list_my_leads_api_v1_leads_mine_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/leads/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Lead Stats */
        get: operations["get_lead_stats_api_v1_leads_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/leads/{lead_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Lead */
        get: operations["get_lead_api_v1_leads__lead_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/leads/{lead_id}/assign": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Assign Lead */
        post: operations["assign_lead_api_v1_leads__lead_id__assign_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/leads/{lead_id}/discard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Discard Lead */
        post: operations["discard_lead_api_v1_leads__lead_id__discard_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rules/scoring": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Scoring Rules */
        get: operations["list_scoring_rules_api_v1_rules_scoring_get"];
        put?: never;
        /** Create Scoring Rule */
        post: operations["create_scoring_rule_api_v1_rules_scoring_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rules/scoring/{rule_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Scoring Rule */
        delete: operations["delete_scoring_rule_api_v1_rules_scoring__rule_id__delete"];
        options?: never;
        head?: never;
        /** Update Scoring Rule */
        patch: operations["update_scoring_rule_api_v1_rules_scoring__rule_id__patch"];
        trace?: never;
    };
    "/api/v1/rules/assignment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Assignment Rules */
        get: operations["list_assignment_rules_api_v1_rules_assignment_get"];
        put?: never;
        /** Create Assignment Rule */
        post: operations["create_assignment_rule_api_v1_rules_assignment_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rules/assignment/{rule_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Assignment Rule */
        delete: operations["delete_assignment_rule_api_v1_rules_assignment__rule_id__delete"];
        options?: never;
        head?: never;
        /** Update Assignment Rule */
        patch: operations["update_assignment_rule_api_v1_rules_assignment__rule_id__patch"];
        trace?: never;
    };
    "/api/v1/rules/disqualification": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Disqualification Rules */
        get: operations["list_disqualification_rules_api_v1_rules_disqualification_get"];
        put?: never;
        /** Create Disqualification Rule */
        post: operations["create_disqualification_rule_api_v1_rules_disqualification_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rules/disqualification/{rule_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Disqualification Rule */
        delete: operations["delete_disqualification_rule_api_v1_rules_disqualification__rule_id__delete"];
        options?: never;
        head?: never;
        /** Update Disqualification Rule */
        patch: operations["update_disqualification_rule_api_v1_rules_disqualification__rule_id__patch"];
        trace?: never;
    };
    "/api/v1/advisors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Advisors */
        get: operations["list_advisors_api_v1_advisors_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/advisors/{agent_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Set Advisor Group */
        patch: operations["set_advisor_group_api_v1_advisors__agent_id__patch"];
        trace?: never;
    };
    "/api/v1/groups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Groups */
        get: operations["list_groups_api_v1_groups_get"];
        put?: never;
        /** Create Group */
        post: operations["create_group_api_v1_groups_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/groups/{group_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Group */
        delete: operations["delete_group_api_v1_groups__group_id__delete"];
        options?: never;
        head?: never;
        /** Update Group */
        patch: operations["update_group_api_v1_groups__group_id__patch"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AdvisorGroupUpdate */
        AdvisorGroupUpdate: {
            /** Group Id */
            group_id: string | null;
        };
        /** AdvisorResponse */
        AdvisorResponse: {
            /** Agent Id */
            agent_id: string;
            /** Name */
            name: string;
            /** Group Id */
            group_id: string | null;
            /** Is Active */
            is_active: boolean;
            /** Active Load */
            active_load: number;
        };
        /** AdvisorsPageResponse */
        AdvisorsPageResponse: {
            /** Items */
            items: components["schemas"]["AdvisorResponse"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Has More */
            has_more: boolean;
        };
        /** AgentLoadResponse */
        AgentLoadResponse: {
            /** Agent Id */
            agent_id: string;
            /** Name */
            name: string;
            /** Active Leads */
            active_leads: number;
        };
        /**
         * AgentMatchMode
         * @description How a rule combines its target group with its named agents.
         *
         *     ANY is the default because the alternative silently drops a named agent
         *     that happens to belong to a different group — the caller asked for that
         *     person explicitly, so excluding them is never what they meant.
         * @enum {string}
         */
        AgentMatchMode: "ANY" | "ONLY";
        /** AppliedRuleResponse */
        AppliedRuleResponse: {
            /** Rule Id */
            rule_id: string;
            /** Name */
            name: string;
            /** Score Delta */
            score_delta: number;
        };
        /** AssignLeadRequest */
        AssignLeadRequest: {
            /**
             * Agent Id
             * Format: uuid
             */
            agent_id: string;
        };
        /** AssignmentRuleCreate */
        AssignmentRuleCreate: {
            /** Name */
            name: string;
            /**
             * Min Score
             * @default 0
             */
            min_score: number;
            /** Max Score */
            max_score?: number | null;
            /** Target Group Id */
            target_group_id?: string | null;
            /** Target Agent Ids */
            target_agent_ids?: string[];
            /** @default ANY */
            agent_match_mode: components["schemas"]["AgentMatchMode"];
            strategy?: components["schemas"]["AssignmentStrategy"] | null;
            /**
             * Priority
             * @default 0
             */
            priority: number;
            /** Conditions */
            conditions?: components["schemas"]["CriterionSchema"][];
        };
        /** AssignmentRuleResponse */
        AssignmentRuleResponse: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Min Score */
            min_score: number;
            /** Max Score */
            max_score?: number | null;
            /** Target Group Id */
            target_group_id?: string | null;
            /** Target Agent Ids */
            target_agent_ids: string[];
            /** Agent Match Mode */
            agent_match_mode: string;
            /** Strategy */
            strategy?: string | null;
            /** Priority */
            priority: number;
            /** Is Active */
            is_active: boolean;
            /** Rr Cursor */
            rr_cursor: number;
            /** Conditions */
            conditions: components["schemas"]["CriterionSchema"][];
        };
        /** AssignmentRuleUpdate */
        AssignmentRuleUpdate: {
            /** Name */
            name?: string | null;
            /** Min Score */
            min_score?: number | null;
            /** Max Score */
            max_score?: number | null;
            /** Target Group Id */
            target_group_id?: string | null;
            /** Target Agent Ids */
            target_agent_ids?: string[] | null;
            agent_match_mode?: components["schemas"]["AgentMatchMode"] | null;
            strategy?: components["schemas"]["AssignmentStrategy"] | null;
            /** Priority */
            priority?: number | null;
            /** Is Active */
            is_active?: boolean | null;
            /** Conditions */
            conditions?: components["schemas"]["CriterionSchema"][] | null;
        };
        /**
         * AssignmentStrategy
         * @enum {string}
         */
        AssignmentStrategy: "ROUND_ROBIN" | "LOWEST_LOAD" | "DIRECT_AGENT";
        /** CriterionSchema */
        CriterionSchema: {
            /** Field */
            field: string;
            operator: components["schemas"]["Operator"];
            /** Value */
            value?: unknown;
        };
        /** DiscardLeadRequest */
        DiscardLeadRequest: {
            /**
             * Reason
             * @default
             */
            reason: string;
        };
        /** DisqualificationRuleCreate */
        DisqualificationRuleCreate: {
            /** Name */
            name: string;
            /** Conditions */
            conditions: components["schemas"]["CriterionSchema"][];
            /**
             * Priority
             * @default 0
             */
            priority: number;
            /**
             * Is Active
             * @default true
             */
            is_active: boolean;
        };
        /** DisqualificationRuleResponse */
        DisqualificationRuleResponse: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Conditions */
            conditions: components["schemas"]["CriterionSchema"][];
            /** Priority */
            priority: number;
            /** Is Active */
            is_active: boolean;
        };
        /** DisqualificationRuleUpdate */
        DisqualificationRuleUpdate: {
            /** Name */
            name?: string | null;
            /** Conditions */
            conditions?: components["schemas"]["CriterionSchema"][] | null;
            /** Priority */
            priority?: number | null;
            /** Is Active */
            is_active?: boolean | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LeadDetailResponse */
        LeadDetailResponse: {
            /** Id */
            id: string;
            /** Tenant Id */
            tenant_id: string;
            /** Source Id */
            source_id: string;
            /** First Name */
            first_name: string;
            /** Last Name */
            last_name: string;
            /** Email */
            email: string | null;
            /** Company */
            company: string;
            /** Budget */
            budget: number;
            /** Industry */
            industry: string;
            /** Custom Attributes */
            custom_attributes: {
                [key: string]: unknown;
            };
            /** Phone */
            phone: string | null;
            /** Score */
            score: number;
            /** Score Breakdown */
            score_breakdown: components["schemas"]["AppliedRuleResponse"][];
            /** Status */
            status: string;
            /** Assigned Agent Id */
            assigned_agent_id: string | null;
            /** Assigned At */
            assigned_at: string | null;
            /** Discard Reason */
            discard_reason: string | null;
            /** Disqualification Reason */
            disqualification_reason?: string | null;
            /** Created At */
            created_at: string;
        };
        /** LeadResponse */
        LeadResponse: {
            /** Id */
            id: string;
            /** Tenant Id */
            tenant_id: string;
            /** Source Id */
            source_id: string;
            /** First Name */
            first_name: string;
            /** Last Name */
            last_name: string;
            /** Email */
            email: string | null;
            /** Company */
            company: string;
            /** Budget */
            budget: number;
            /** Industry */
            industry: string;
            /** Custom Attributes */
            custom_attributes: {
                [key: string]: unknown;
            };
            /** Phone */
            phone: string | null;
            /** Score */
            score: number;
            /** Status */
            status: string;
            /** Assigned Agent Id */
            assigned_agent_id: string | null;
            /** Created At */
            created_at: string;
            /** Updated At */
            updated_at: string;
        };
        /** LeadStatsResponse */
        LeadStatsResponse: {
            /** Total */
            total: number;
            /** By Status */
            by_status: {
                [key: string]: number;
            };
            /** Unassigned */
            unassigned: number;
            /** Load By Agent */
            load_by_agent: components["schemas"]["AgentLoadResponse"][];
        };
        /**
         * Operator
         * @enum {string}
         */
        Operator: "EQUALS" | "NOT_EQUALS" | "GREATER_THAN" | "LESS_THAN" | "CONTAINS" | "IN" | "IS_EMPTY" | "IS_NOT_EMPTY";
        /** PaginatedAssignmentRulesResponse */
        PaginatedAssignmentRulesResponse: {
            /** Items */
            items: components["schemas"]["AssignmentRuleResponse"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Has More */
            has_more: boolean;
        };
        /** PaginatedDisqualificationRulesResponse */
        PaginatedDisqualificationRulesResponse: {
            /** Items */
            items: components["schemas"]["DisqualificationRuleResponse"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Has More */
            has_more: boolean;
        };
        /** PaginatedGroupsResponse */
        PaginatedGroupsResponse: {
            /** Items */
            items: components["schemas"]["SalesGroupResponse"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Has More */
            has_more: boolean;
        };
        /** PaginatedLeadsResponse */
        PaginatedLeadsResponse: {
            /** Items */
            items: components["schemas"]["LeadResponse"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Has More */
            has_more: boolean;
        };
        /** PaginatedScoringRulesResponse */
        PaginatedScoringRulesResponse: {
            /** Items */
            items: components["schemas"]["ScoringRuleResponse"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Has More */
            has_more: boolean;
        };
        /** SalesGroupCreate */
        SalesGroupCreate: {
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /** @default LOWEST_LOAD */
            default_strategy: components["schemas"]["AssignmentStrategy"];
            /** Capacity Per Agent */
            capacity_per_agent?: number | null;
        };
        /** SalesGroupResponse */
        SalesGroupResponse: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /** Default Strategy */
            default_strategy: string;
            /** Capacity Per Agent */
            capacity_per_agent?: number | null;
            /** Is Active */
            is_active: boolean;
            /** Agent Count */
            agent_count?: number | null;
        };
        /** SalesGroupUpdate */
        SalesGroupUpdate: {
            /** Name */
            name?: string | null;
            /** Description */
            description?: string | null;
            default_strategy?: components["schemas"]["AssignmentStrategy"] | null;
            /** Capacity Per Agent */
            capacity_per_agent?: number | null;
            /** Is Active */
            is_active?: boolean | null;
        };
        /** ScoringRuleCreate */
        ScoringRuleCreate: {
            /** Name */
            name: string;
            /** Conditions */
            conditions: components["schemas"]["CriterionSchema"][];
            /** Score Delta */
            score_delta: number;
            /**
             * Priority
             * @default 0
             */
            priority: number;
            /**
             * Is Active
             * @default true
             */
            is_active: boolean;
        };
        /** ScoringRuleResponse */
        ScoringRuleResponse: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Conditions */
            conditions: components["schemas"]["CriterionSchema"][];
            /** Score Delta */
            score_delta: number;
            /** Priority */
            priority: number;
            /** Is Active */
            is_active: boolean;
        };
        /** ScoringRuleUpdate */
        ScoringRuleUpdate: {
            /** Name */
            name?: string | null;
            /** Conditions */
            conditions?: components["schemas"]["CriterionSchema"][] | null;
            /** Score Delta */
            score_delta?: number | null;
            /** Priority */
            priority?: number | null;
            /** Is Active */
            is_active?: boolean | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    list_leads_api_v1_leads_get: {
        parameters: {
            query?: {
                status?: string | null;
                assigned_agent_id?: string | null;
                group_id?: string | null;
                source_id?: string | null;
                q?: string | null;
                updated_since?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedLeadsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_my_leads_api_v1_leads_mine_get: {
        parameters: {
            query?: {
                status?: string | null;
                q?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedLeadsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_lead_stats_api_v1_leads_stats_get: {
        parameters: {
            query?: {
                from?: string | null;
                to?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeadStatsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_lead_api_v1_leads__lead_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lead_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeadDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    assign_lead_api_v1_leads__lead_id__assign_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lead_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssignLeadRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeadDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    discard_lead_api_v1_leads__lead_id__discard_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lead_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DiscardLeadRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeadDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_scoring_rules_api_v1_rules_scoring_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedScoringRulesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_scoring_rule_api_v1_rules_scoring_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScoringRuleCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScoringRuleResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_scoring_rule_api_v1_rules_scoring__rule_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rule_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_scoring_rule_api_v1_rules_scoring__rule_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rule_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScoringRuleUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScoringRuleResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_assignment_rules_api_v1_rules_assignment_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedAssignmentRulesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_assignment_rule_api_v1_rules_assignment_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssignmentRuleCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssignmentRuleResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_assignment_rule_api_v1_rules_assignment__rule_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rule_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_assignment_rule_api_v1_rules_assignment__rule_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rule_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssignmentRuleUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssignmentRuleResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_disqualification_rules_api_v1_rules_disqualification_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedDisqualificationRulesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_disqualification_rule_api_v1_rules_disqualification_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DisqualificationRuleCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DisqualificationRuleResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_disqualification_rule_api_v1_rules_disqualification__rule_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rule_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_disqualification_rule_api_v1_rules_disqualification__rule_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rule_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DisqualificationRuleUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DisqualificationRuleResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_advisors_api_v1_advisors_get: {
        parameters: {
            query?: {
                group_id?: string | null;
                is_active?: boolean | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdvisorsPageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_advisor_group_api_v1_advisors__agent_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agent_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdvisorGroupUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdvisorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_groups_api_v1_groups_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedGroupsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_group_api_v1_groups_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SalesGroupCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SalesGroupResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_group_api_v1_groups__group_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                group_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_group_api_v1_groups__group_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                group_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SalesGroupUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SalesGroupResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
